name: my_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cpf_cnpj_validator: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0 #Para usar o Either<Error, Success> no repositorio
  email_validator: ^2.0.1
  equatable: ^2.0.3 #Faz override do hashcode de instancias de uma mesma classe quando comparada uma com a outra
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2 #Gerenciador de estado
  flutter_modular: ^3.0.0-nullsafety.3 #Injeção de dependências
  flutter_modular_test: ^1.0.4 #Auxiliar do Injeção de dependências
  flutter_native_splash: ^1.3.2 #Splash screen
  geocoding: ^2.0.1 #Pega endereço pelo sua localização
  google_fonts: ^2.1.0
  http: ^0.13.4
  intl: ^0.17.0
  location: ^4.3.0 #Pega endereço pelo sua localização
  mask_text_input_formatter: ^2.0.0
  mobx: ^2.0.5 #Auxiliar Gerenciador de estado
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.9 #Guardar cache no celular
  image_picker: ^0.8.4+4
  # flutter_credit_card: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.5 #Auxiliar para o gerenciador de estado
  flutter_launcher_icons: "^0.9.2" #Icone do aplicativo na area de trabalho
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4 #Auxiliar para o gerenciador de estado
  mocktail: ^0.2.0 #Mockar dados para testes unitarios

flutter_native_splash:
  image: assets/splash.png
  color: "FFFFFF"
  fill: true
  android: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/images/
    - assets/images/announcement/
    - assets/images/stores/
    - assets/images/services_purchase/
    - assets/icon/
    - assets/icon/payment_methods_icons/
    - assets/logos/
    - assets/backgrounds/
    - assets/products_type/
    - assets/images/product_announcement/
    - assets/images/product_announcement/product_categories/

  uses-material-design: true
