// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkgBb7oKKXhNzfSyoYqmNu8VpAcEomB24',
    appId: '1:362509356465:web:f924c6b7443ce91df28190',
    messagingSenderId: '362509356465',
    projectId: 'vivassimo-dev',
    authDomain: 'vivassimo-dev.firebaseapp.com',
    storageBucket: 'vivassimo-dev.appspot.com',
    measurementId: 'G-0SSC7PTL8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3m-khRYDXof2DFV6dye7hPx9GuURAl8',
    appId: '1:362509356465:android:a1f83abdaffa3c05f28190',
    messagingSenderId: '362509356465',
    projectId: 'vivassimo-dev',
    storageBucket: 'vivassimo-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqWIHCMzEYtsWMZf5cPpn2g30Jc_tyMI4',
    appId: '1:362509356465:ios:3704ed532828ae99f28190',
    messagingSenderId: '362509356465',
    projectId: 'vivassimo-dev',
    storageBucket: 'vivassimo-dev.appspot.com',
    iosClientId: '362509356465-3qngumrtapr0eel51iu33drfmfrs5jgq.apps.googleusercontent.com',
    iosBundleId: 'com.unibes.vivassimo.dev',
  );
}
